### ISSUE TITLE
philosopher stones!

### ISSUE THREAD

**Issue by AuraGuy** [Gstayton/GeometricMagic#3]
in a recent update the fire and portal blocks have been removed from the game, this makes it impossible to create a philosophers stone ;-;
is there any fix for this or are you planning on updating the plugin with this bug fixed?

i love the plugin overall, it's just sad that i can't change all of my friends into beautifull alchemy-boosting stones ;-;

if i may suggest replacements blocks: bedrock for a philosophers stone and heads for souls

**Comment by Gstayton** [comment]
I dropped working on this when bukkit kicked the proverbial bucket. However, I might pick this up again once I finish a few current projects. I might be able to throw out a patch for this in short order, if you could to tell me what server you're currently running? There are a few libraries I will need to patch out as well that died with bukkit. Glad to hear people still use this though!

Edit: Seems that while AntiCheat was discontinued, there is a fork that GeometricMagic might yet build against. There's also the fact that Vault is still in active development, so I might be in luck.

Not too keen on adding in Bedrock as a mod-block, because then I have to keep them from being placed in the world; And there are _tons_ of ways to get heads in Minecraft already, so using them as a rare, hard-to-get item is not wise either. Looking into solutions, but I can't spend a ton of time on this, but I do have other things that need more immediate attention coming up. Sorry 'bout that.

Edit-v2: I'll also need to know what version you are running, as I haven't kept up with when Minecraft block changes have occurred (I've been out of the loop for a long time now...)

**Comment by Gstayton** [comment]
Okay. So, changed it to use a meta-data based system. Now uses bones renamed to Souls for souls, and a Nether Star renamed to Philosphers Stone. Also messed around with adding lore to them. Haven't really had much time to test it, but I want to take some time to relax before I work this weekend, so either you can compile from the Bukkit-1.8.8 branch (Even if you're using an older version, it should work. It doesn't use anything newer than the versions you'd have access to anyways), or you can trust me not to host malicious files and download https://mega.nz/#!CYBVhQgD!OzHLM1qBZ45CJIzTqWOKK5r0BENuEtDAVXORa9XHh4M <- that.

I recommend doing some testing on it before using it heavily, and if there are any problems don't hesitate to ask. This is one of my favorite plugins, and I love to know people are still using it. Sorry I can't give it as much love as it deserves!

**Comment by AuraGuy** [comment]
Thank you for the quick response and the extremely quick fix, I'll start testing it today and I will let you know if there are any problems!

it says i need a decoding key in order to download it.
can you please give me the key or make it a public file?

**Comment by Gstayton** [comment]
Apologies. Link is updated.

Edit: Or I could not have actually submitted the updated link, be laying in bed browsing github issues, look back at  this and realize I dun goofed. Sorry 'bout that.

**Comment by AuraGuy** [comment]
it might just me being a complete idiot but for some reason i cannot turn the souls into philosophers stones. I will include a video link https://www.youtube.com/watch?v=sU32XJy5xlo  <---- here!

here is the server log: http://m.uploadedit.com/ba3m/1446915735933.txt
Norton might say that the site is not safe, but there is nothing wrong with it as far as i know >.>

**Comment by Gstayton** [comment]
Probably nothing wrong on your part. [This](https://github.com/Gstayton/GeometricMagic/blob/bukkit-1.8.8/src/me/cakenggt/GeometricMagic/GeometricMagicPlayerListener.java#L1107) line a bug I had thought I'd fixed, resulting in a lot of skipping things that needed to happen if you had the permission bypass.hunger, which as an op you'd have. Ran into the same issue when I tested, so no worries. Fixed in 885be4c.

Also fixed was the fact that I forgot to set the meta to the [item](https://github.com/Gstayton/GeometricMagic/blob/bukkit-1.8.8/src/me/cakenggt/GeometricMagic/GeometricMagicPlayerListener.java#L1067), so you would've just gotten a nether star with no special properties even if that bug hadn't cropped up... So yeah. Thanks for sticking with me through this.

[Here](https://mega.nz/#!SBIgRBJC!gplfE4MDDQJHVUaFZirdEci2Al7Xo4yjUR7vNGMt3SU) is the new jar, will have to look into updating the bukkit page for this mod soon, but for now it's just mega. Updating mods on there takes a while anyways.

**Comment by AuraGuy** [comment]
hey Gstayton, thank you for the quick fix, i can finally make philosophers stones from my friends' souls ^^
anyways, i have found a slight bug which does not require direct fixing but i think i might as well let you know: souls do not heal you when you hit zero health! 

so again, thank you for everything, my friends and i are having a ton of fun with this plugin!

**Comment by Gstayton** [comment]
Amusingly, I don't even much remember that feature... If it's not terribly required, anything non game-breaking will probably be put off. After I finish a few other things I'm working on, now that I know this mod still sees some use, I'll probably dive back into the total re-write of the codebase.

Anyways, issue resolved, closing it now. Glad I could fix things for ya.
